= Test Asciidoc 1
:toc:

== Introduction
A test asciidoc to exercise cljdoc formatting and features.

== Formatting marks

I have a *strong* feeling that I might be head**strong**.

I am _under_ the impression that that you are th__under__struck by this example.

My `code` was en```coded```ed.


== Code blocks

.code-block-title
[source,clojure]
----
;; some sweet clojure code

(defn hello-earthling
  "Greet an earthling in a believable way."  ;; <1>
  [name]
  (println "Hello earthling " (uppercase name))) ;; <2>
----
<1> a docstring comes before the arguments
<2> check with an earthling if uppercasing is soothing


== Admonitions

NOTE: Note that this note is a note.

TIP: Tip the scales with a tip.

IMPORTANT: Important things are said here.

CAUTION: Aren't you a caution?

WARNING: Warning to the wise.

== Tables

Asciidoc tables are quite full featured.

.A nested table example from asciidoctor user manual
[cols="1,2a"]
|===
| Col 1 | Col 2

| Cell 1.1
| Cell 1.2

| Cell 2.1
| Cell 2.2

[cols="2,1"]
!===
! Col1 ! Col2

! C11
! C12

!===

|===

== Links

https://cljdoc.org/d/$group-id$/$artifact-id/CURRENT/api/$artifact-id$.core/exercise[A link to my cljdoc-exerciser/core.exercise]
